### ISSUE TITLE
Distorção na formatação do numberInput

### ISSUE THREAD

**Issue by TerezaAlmeida** [rsg73626/framework-frontend-responsivo-acessivel#3]
Boa tarde, Renan. Tudo bem?
Aqui é a Tereza aluna do TCC II da professora Maria Amélia que está realizando os testes de acessibilidade num site criado à partir do ACCEASY. 
Renan, eu atualizei o código do framework para que os ajustes que realizou fossem contemplados para mim, porém essa atualização acabou alterando as páginas do site onde tinham as atividades de soma, subtração, multiplicação e divisão. Em anexo vou deixar imagens do Antes e Depois da página da atividade de soma. Será que poderia me ajudar?
Nesses itens que estão distorcidos eu utilizo a função "numberInputs", em anexo no arquivo "scriptAtividadeSoma.txt" tem o código em JavaScript que utilizei nessa página.
![Depois](https://user-images.githubusercontent.com/51377207/98160643-38786a80-1ebd-11eb-9d33-bf2a2c8593e2.PNG)

![Antes](https://user-images.githubusercontent.com/51377207/98160619-30202f80-1ebd-11eb-93e4-86942aa488d3.PNG)

[scriptAtividadeSoma.txt](https://github.com/rsg73626/acceasy/files/5490128/scriptAtividadeSoma.txt)

**Comment by rsg73626** [comment]
Boa noite Tereza.

Desculpa a demora para te responder.

Eu baixei o código do Acceasy, da master, e usei o código do arquivo que vc baixou dentro da página que eu disponibilizo de exemplo, e tudo funcionou corretamente. Testei no Google Chrome e no Safari.

Se você continuar com o erro e quiser fazer uma call para me mostrar podemos marcar também.

Obrigado,

Renan.

________________________________
De: TerezaAlmeida <notifications@github.com>
Enviado: quarta-feira, 4 de novembro de 2020 19:46
Para: rsg73626/acceasy <acceasy@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Assunto: [rsg73626/acceasy] Distorção na formatação do numberInput (#3)


Boa tarde, Renan. Tudo bem?
Aqui é a Tereza aluna do TCC II da professora Maria Amélia que está realizando os testes de acessibilidade num site criado à partir do ACCEASY.
Renan, eu atualizei o código do framework para que os ajustes que realizou fossem contemplados para mim, porém essa atualização acabou alterando as páginas do site onde tinham as atividades de soma, subtração, multiplicação e divisão. Em anexo vou deixar imagens do Antes e Depois da página da atividade de soma. Será que poderia me ajudar?
Nesses itens que estão distorcidos eu utilizo a função "numberInputs", em anexo no arquivo "scriptAtividadeSoma.txt" tem o código em JavaScript que utilizei nessa página.
[Depois]<https://user-images.githubusercontent.com/51377207/98160643-38786a80-1ebd-11eb-9d33-bf2a2c8593e2.PNG>

[Antes]<https://user-images.githubusercontent.com/51377207/98160619-30202f80-1ebd-11eb-93e4-86942aa488d3.PNG>

scriptAtividadeSoma.txt<https://github.com/rsg73626/acceasy/files/5490128/scriptAtividadeSoma.txt>

**Comment by TerezaAlmeida** [comment]
Obrigada pela devolutiva, irei continuar analisando e qualquer coisa entro em contato novamente.

**Comment by TerezaAlmeida** [comment]
Obrigada pela devolutiva, irei continuar analisando e qualquer coisa entro em contato novamente.
Enquanto isso, irei encerrar essa issue.
